export {
  Options,
  Plugin,
  GeneratedFile,
  JSImportPath,
  JSIdent,
  defaultJSImportFunc,
} from "./framework";
export type { Extension } from "./descriptor";
export {
  Cardinality,
  Enum,
  EnumOptions,
  EnumValue,
  EnumValueOptions,
  Field,
  FieldOptions,
  File,
  FileOptions,
  Kind,
  Location,
  Message,
  MessageOptions,
  Method,
  MethodOptions,
  Oneof,
  OneofOptions,
  Service,
  ServiceOptions,
} from "./descriptor";
