name: Prettier

on:
  push:
    branches: [main, gh-actions]
  pull_request:
    branches: [main, gh-actions]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: prettier --version
        run: npm exec prettier -- --version

      - name: Run prettier
        run: npm run lint
