on:
  release:
    types:
      - published

name: NPM Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: node --version
        run: node --version

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm whoami

      # "npm publish" runs "npm pack" that runs, because of the prepack script
      # in package.json, a clean build.
      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
