name: Test

on:
  push:
    branches: [main, gh-actions]
  pull_request:
    branches: [main, gh-actions]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: node --version
        run: node --version

      - name: Setup protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.17.3"
      - name: protoc --version
        run: protoc --version

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm exec mocha -- lib/test --recursive --exit
